id: opecha:P000409
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15516
  title: དཔལ་མཉམ་མེད་མར་པ་བཀའ་བརྒྱུད་ཀྱི་གྲུབ་པའི་མཐའ་རྣམ་པར་ངེས་པར་བྱེད་པ་མདོར་བསྡུས་སུ་བརྗོད་པ་དྭགས་བརྒྱུད་གྲུབ་པའི་མེ་ལོང་།
  volume: ''
  author: ''
